# Generated by Django 5.0 on 2023-12-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cloth_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=100, verbose_name='product details')),
                ('cat', models.IntegerField(choices=[(1, 'One Piece'), (2, 'Lehengas'), (3, 'Sarees'), (4, 'Suits'), (5, 'Shirts'), (6, 'Jeans'), (7, 'Crop Tops')], verbose_name='category')),
                ('occa', models.IntegerField(choices=[(1, 'Anniversary'), (2, 'Birthday Party'), (3, 'Bachelorette Party'), (4, 'Independence Day'), (5, 'Wedding')], verbose_name='occassion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
