# Generated by Django 5.0 on 2023-12-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth_product',
            name='occa',
            field=models.IntegerField(choices=[(1, 'Anniversary'), (2, 'Birthday Party'), (3, 'Bachelorette Party'), (4, 'Independence Day'), (5, 'Wedding'), (6, 'Daily Wear')], verbose_name='occassion'),
        ),
    ]
