# Generated by Django 5.0 on 2023-12-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0003_addcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth_product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'One Piece'), (2, 'Lehengas'), (3, 'Sarees'), (4, 'Suits'), (5, 'Shirts'), (6, 'Jeans'), (7, 'Crop Tops'), (8, 'Daily Wear')], verbose_name='category'),
        ),
    ]
