# Generated by Django 5.0 on 2023-12-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
