# Generated by Django 5.0 on 2023-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='contactor name')),
                ('email', models.CharField(max_length=50, verbose_name='contactor email')),
                ('message', models.CharField(max_length=500, verbose_name='contactor message')),
            ],
        ),
    ]
