# Generated by Django 4.2.7 on 2023-12-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0012_orderconfirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderConfirmed',
        ),
    ]
